### ISSUE TITLE
Assigment inside Condition possible

### ISSUE THREAD

**Issue by ralf1307** [martin-pabst/Online-IDE#10]
```java
boolean test = false;

if(test = true) {
   
}
```

**Comment by martin-pabst** [comment]
The assignment operator in Java returns the assigned value (see [this stackoverflow thread](https://stackoverflow.com/questions/38163938/return-value-of-assignment-operation-in-java)), therefore your example is syntactically correct. I agree that in most cases this scenario roots in a misunderstanding (= instead of ==), therefore i changed compiler behaviour to issue a warning.
