### ISSUE TITLE
Multiline-comments: Problems with starting a comment after a tab

### ISSUE THREAD

**Issue by ThatVillagerGuy** [martin-pabst/Online-IDE#13]
When creating a multiline-comment, every new line starts with an asterisk, however by not creating the comment at the beginning of the line, the start of the comment '/*' gets formatted to the beginning of the line and thisway breaks the comment and new lines don't start with an asterisk anymore.

**Comment by ralf1307** [comment]
My guess is that Monaco cant handle "new-bullets" with an indent.
https://github.com/martin-pabst/Online-IDE/blob/6f8cb72ab17048acd0176d98421d191c41bc438a/src/client/main/gui/Editor.ts#L365

**Comment by martin-pabst** [comment]
@ralf1307: Thank you for the hint! There's another sourcecode-location responsible for inserting additional comment lines:
https://github.com/martin-pabst/Online-IDE/blob/6f8cb72ab17048acd0176d98421d191c41bc438a/src/client/main/gui/MyJava.ts#L18-L45

The root cause of the problem was the auto-formatter outdenting the first line of the comment. I disabled this behaviour.
