### ISSUE TITLE
Problem regarding embeded code on LearnJ

### ISSUE THREAD

**Issue by ThatVillagerGuy** [martin-pabst/Online-IDE#16]
On the site about the act method there are problems with <span> tags inside the embeded code
https://learnj.de/doku.php?id=api:documentation:grafik:animation&s[]=act
![image](https://user-images.githubusercontent.com/53975292/118534197-40a54280-b749-11eb-8f9b-8b2e191197da.png)

**Comment by martin-pabst** [comment]
This problem is caused by dokuwiki's search functionality: If search for "act" dokuwiki marks all occurrences of this word on the page found and doesn't refrain from inserting html-code into <script>-tags. Visit the page again without search and you won't see this tag again.
I'll try to raise an issue at the dokuwiki project.
