### ISSUE TITLE
online-ide.de is down?

### ISSUE THREAD

**Issue by Entkenntnis** [martin-pabst/Online-IDE#62]
Hi Martin,

I'm currently not able to reach https://online-ide.de/ - the connection is timing out. Could you possibly look into this?

Thanks!

**Comment by martin-pabst** [comment]
I'll look into it. There seems to be a hardware problem with the network interface. I'm confident to get it up running till tomorrow morning (15.11.2022).

**Comment by martin-pabst** [comment]
My hoster has solved its network problem.  Online-IDE and SQL-IDE are working again. 
Please apologize the inconveniance.

**Comment by Entkenntnis** [comment]
Thank you for the fast response and resolution - the online-IDE is working again.

**Comment by martin-pabst** [comment]
There had been disruptions in contabo's Düsseldorf data center which caused major network problems from monday, november 14th 2022 till today (wednesday, november 16th). Below i'll copy the latests statements from [https://contabo-status.de/](https://contabo-status.de/).

The online IDE is running fine since 8 o'clock this morning. 

I hope the specialists at contabo are able to find the root cause of the problem soon. 

[https://contabo-status.de/](https://contabo-status.de/)

"16.11.2022 08:00 Packet loss and slow connections in Duesseldorf data center
Voraussichtliche Dauer: 120 Minuten
We are currently investigating packet loss and slow connection issues in our Duesseldorf data center. Our specialists are looking into this at the moment. An update will follow at 09:00 CET at the latest.
[UPDATE 16.11.2022 08:58]

Our specialists were able to identify the root cause of this, connections are stabilizing again, but we are still monitoring the network stability. Next update will follow at 10:00 CET.
[UPDATE 16.11.2022 10:10]

Network has stabilized again, but we are still investigating unavailability of servers with IPs within the 109.123.254.0/24 subnet. Next update on that will follow at 11:00 CET.
[UPDATE 16.11.2022 12:15]

Servers from IP range 109.123.254.0/24 should now be reachable again as well. Situation is still monitored closely.
15.11.2022 16:03  Disruption in our Data Center in Duesseldorf
Voraussichtliche Dauer: 180 Minuten
We are experiencing a disruption in our Data Center in Duesseldorf. We’re sorry for the inconvenience. Our engineer are already working on the solution.
Next update will be published at 17:00 CET.****"
